### ISSUE TITLE
Need a way to pass `requireLibrary`/`requireLibraries` to the Asciidoctor instance

### ISSUE THREAD

**Issue by johnrengelman** [craigburke/asciidoctor-asset-pipeline#1]
so we can add things like `asciidoctorj-diagram`.

**Comment by johnrengelman** [comment]
I tried to put together a PR for this, but when I run `gradlew publishToMavenLocal`, it doesn't seem to work correctly. The `.adoc` files don't get converted to `.html` and on first run I get:

```
:clientInstall UP-TO-DATE
:assetCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assetCompile'.
> java.io.FileNotFoundException: JAR entry META-INF/asset-pipeline/asset.specs not found in /Users/john/.m2/repository/com/craigburke/asciidoctor-asset-pipeline/1.0.1-SNAPSHOT/asciidoctor-asset-pipeline-1.0.1-SNAPSHOT.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

A subsequent run, doesn't have this error, but the files are not converted

**Comment by craigburke** [comment]
Damnit, @johnrengelman what did you do!??!

**Comment by craigburke** [comment]
I'm working on this now actually. It needs work. 
<img width="539" alt="screen shot 2016-06-20 at 10 12 12 pm" src="https://cloud.githubusercontent.com/assets/793574/16215908/47fa1ea6-3734-11e6-854a-21a8d98eaca4.png">

**Comment by craigburke** [comment]
Holy shit! I got it working!

<img width="696" alt="screen shot 2016-06-21 at 8 16 16 am" src="https://cloud.githubusercontent.com/assets/793574/16229017/7b423af6-3788-11e6-8c4f-2abbda6e37b1.png">

**Comment by craigburke** [comment]
@johnrengelman do you have it listed in your buildscript classpath (need to update the README until I can submit a PR to the asset pipeline to add it automatically)?

**Comment by johnrengelman** [comment]
I do....

```
buildscript {
    ext {
        assetPipelineVersion = '2.9.0'
    }
    repositories {
        mavenLocal()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'io.ratpack:ratpack-gradle:1.3.3'
        classpath 'com.craigburke.gradle:client-dependencies:1.1.3'
        classpath 'com.craigburke:asciidoctor-asset-pipeline:1.0.0'
        classpath "com.bertramlabs.plugins:asset-pipeline-gradle:${assetPipelineVersion}"
        classpath 'org.ajoberstar:gradle-git:1.5.0'
        classpath 'org.asciidoctor:asciidoctorj-diagram:1.3.1'
    }
}
```

that doesn't seem to work.

This in my file:

```
[graphviz, dot-example, svg]
----
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
----
```

and I get this error:
`asciidoctor: WARNING: <stdin>: line 28: invalid style for listing block: graphviz`

**Comment by craigburke** [comment]
@johnrengelman I have some changes to push that should help. I did need to set the imagesoutdir attribute so the images were generated in the asset root. I'll clean up my code and give you a working example.

**Comment by craigburke** [comment]
I'll close this for now. Right now asciidoctor-diagram is automatically loaded but I'll revisit the idea of loading other libraries if we need to.
