### ISSUE TITLE
Including multiple tags doesn't add new line between tag blocks

### ISSUE THREAD

**Issue by johnrengelman** [craigburke/asciidoctor-asset-pipeline#3]
When using multiple tags in an include, the first line of each block is on the same line as the last line of the previous block.

**Comment by craigburke** [comment]
WUT?

**Comment by craigburke** [comment]
Example from @johnrengelman 

`include::Foo.groovy[tags=foo;bar]`

and in doc

```
// tag::foo[]
jar {
  baseName = 'foo'
}
// end::foo[]

// tag::bar[]
jar {
  classified = ''
}
// end::bar[]
```

that should get rendered as:

```
jar {
  baseName = 'foo'
}
jar {
  classified = ''
}
```

but instead it gets rendered as:

```
jar {
  baseName = 'foo'
}jar{
  classified = ''
}
```
